# # src/worker.py
# """
# Callback routing and validation logic for the M-Pesa Gateway Worker.

# This module is deliberately free of Cloudflare entrypoint code.
# It only knows how to parse and validate incoming callback requests.
# """

# from workers import Response


# class CallbackRouter:
#     """
#     Parses and validates incoming M-Pesa callback requests.

#     Responsibilities:
#     - Enforce HTTP method (POST only)
#     - Match the expected path pattern
#     - Extract the opaque integration_id and event_type
#     - Perform basic validation of the integration_id format

#     Expected URL patterns:
#         POST /mpesa/cb/{integration_id}/validation
#         POST /mpesa/cb/{integration_id}/confirmation
#     """

#     # Only these two event types are accepted by the gateway
#     ALLOWED_EVENTS = {"validation", "confirmation"}

#     def __init__(self, request):
#         """
#         Args:
#             request: The incoming Cloudflare Worker request object.
#         """
#         self.request = request
#         self.integration_id = None  # e.g. "gw_7xK92mPq"
#         self.event_type = None  # "validation" or "confirmation"
#         self.error_response = None  # Response object when validation fails

#     def parse(self) -> bool:
#         """
#         Attempt to parse and validate the request.

#         Returns:
#             True  → request is valid; integration_id and event_type are set.
#             False → request is invalid; error_response is set and should be returned.
#         """
#         # 1. Method must be POST
#         if self.request.method != "POST":
#             self.error_response = Response("Method Not Allowed", status=405)
#             return False

#         # 2. Normalise path (remove trailing slash)
#         path = self.request.url.path.rstrip("/")
#         parts = path.split("/")

#         # Expected shape after split:
#         #   ['', 'mpesa', 'cb', '{integration_id}', '{event_type}']
#         # Index: 0    1       2    3                 4
#         if len(parts) != 5 or parts[1] != "mpesa" or parts[2] != "cb":
#             self.error_response = Response("Not Found", status=404)
#             return False

#         integration_id = parts[3]
#         event_type = parts[4]

#         # 3. Event type must be one of the allowed values
#         if event_type not in self.ALLOWED_EVENTS:
#             self.error_response = Response("Not Found", status=404)
#             return False

#         # 4. Soft validation of the opaque integration identifier.
#         #    We expect IDs generated by the gateway to start with "gw_".
#         #    This can be tightened later when a real registry exists.
#         if not integration_id or not integration_id.startswith("gw_"):
#             self.error_response = Response("Invalid integration identifier", status=400)
#             return False

#         # All checks passed — store the extracted values
#         self.integration_id = integration_id
#         self.event_type = event_type
#         return True

"""
Callback routing and validation logic for the M-Pesa Gateway Worker.

This module is deliberately free of Cloudflare entrypoint code.
It only knows how to parse and validate incoming callback requests.
"""

from urllib.parse import urlparse
from workers import Response


class CallbackRouter:
    """
    Parses and validates incoming M-Pesa callback requests.

    Responsibilities:
    - Enforce HTTP method (POST only)
    - Match the expected path pattern
    - Extract the opaque integration_id and event_type
    - Perform basic validation of the integration_id format

    Expected URL patterns:
        POST /mpesa/cb/{integration_id}/validation
        POST /mpesa/cb/{integration_id}/confirmation
    """

    # Only these two event types are accepted by the gateway
    ALLOWED_EVENTS = {"validation", "confirmation"}

    def __init__(self, request):
        """
        Args:
            request: The incoming Cloudflare Worker request object.
        """
        self.request = request
        self.integration_id = None  # e.g. "gw_7xK92mPq"
        self.event_type = None  # "validation" or "confirmation"
        self.error_response = None  # Response object when validation fails

    def parse(self) -> bool:
        """
        Attempt to parse and validate the request.

        Returns:
            True  → request is valid; integration_id and event_type are set.
            False → request is invalid; error_response is set and should be returned.
        """
        # 1. Method must be POST
        if self.request.method != "POST":
            self.error_response = Response("Method Not Allowed", status=405)
            return False

        # 2. Extract path from the URL string
        #    In Cloudflare Python Workers, request.url is a plain string,
        #    not a URL object. We therefore parse it ourselves.
        parsed = urlparse(self.request.url)
        path = parsed.path.rstrip("/")
        parts = path.split("/")

        # Expected shape after split:
        #   ['', 'mpesa', 'cb', '{integration_id}', '{event_type}']
        # Index: 0    1       2    3                 4
        if len(parts) != 5 or parts[1] != "mpesa" or parts[2] != "cb":
            self.error_response = Response("Not Found", status=404)
            return False

        integration_id = parts[3]
        event_type = parts[4]

        # 3. Event type must be one of the allowed values
        if event_type not in self.ALLOWED_EVENTS:
            self.error_response = Response("Not Found", status=404)
            return False

        # 4. Soft validation of the opaque integration identifier.
        #    We expect IDs generated by the gateway to start with "gw_".
        #    This can be tightened later when a real registry exists.
        if not integration_id or not integration_id.startswith("gw_"):
            self.error_response = Response("Invalid integration identifier", status=400)
            return False

        # All checks passed — store the extracted values
        self.integration_id = integration_id
        self.event_type = event_type
        return True
